#!/bin/bash
#This script uninstalls arduino and ino tools
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
LANG=C perl -e exit
echo Uninstalling Arduino ...
sudo apt-get -y remove arduino
echo Uninstalling ino tools ...
pip uninstall ino
sleep 2